project:
  type: website

website:
  title: "Finding Earth 2.0: Predicting Exoplanet Habitability"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methodology.qmd
        text: Methodology
      - about.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    page-layout: full
    include-in-header:
      - text: |
          <style>
          :root {
            --quarto-hl-kw-color: #7dd3fc;
            --quarto-hl-st-color: #f8fafc;
          }
          </style>



